name: app_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.1.0+11

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  cloud_firestore: ^4.15.6
  firebase_core: ^2.25.5
  flutter_svg: ^2.0.9
  ionicons: ^0.2.1
  line_icons: ^2.0.3
  html_editor_enhanced: ^2.5.1
  pointer_interceptor: ^0.9.3+7
  youtube_parser: ^2.1.3
  firebase_auth: ^4.17.6
  data_table_2: ^2.5.11
  firebase_ui_firestore: ^1.6.2
  cached_network_image: ^3.3.1
  intl: ^0.18.0
  url_strategy: ^0.2.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.7
  dotted_border: ^2.1.0
  file_picker: ^5.5.0
  url_launcher: ^6.2.5
  http: ^0.13.6
  loading_animation_widget: ^1.2.0+4
  animated_flip_counter: ^0.2.6
  flutter_riverpod: ^2.4.9
  csv: ^6.0.0
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  fl_chart: ^0.66.2
  rounded_loading_button:
    git:
      url: https://github.com/scopendo/flutter_rounded_loading_button
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/user_avatars/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/google_fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Poppins-ExtraBold.ttf
          weight: 800




