name: app_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.1.0+11

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: 6.1.2
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  flutter_svg: ^2.0.10+1
  ionicons: ^0.2.2
  line_icons: 2.0.3
  html_editor_enhanced: 2.5.1
  pointer_interceptor: 0.9.3+7
  youtube_parser: ^2.1.4
  firebase_auth: ^4.19.5
  data_table_2: ^2.5.12
  firebase_ui_firestore: ^1.6.3
  cached_network_image: 3.3.1
  intl: 
  url_strategy: 0.2.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  dotted_border: 2.1.0
  file_picker: 5.5.0
  url_launcher: ^6.2.6
  http: ^1.2.1
  loading_animation_widget: ^1.2.1
  animated_flip_counter: ^0.3.4
  flutter_riverpod: ^2.5.1
  csv: 6.0.0
  html_unescape: 2.0.0
  flutter_html: ^3.0.0-beta.2
  fl_chart: 
  rounded_loading_button:
    git:
      url: https://github.com/scopendo/flutter_rounded_loading_button
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/user_avatars/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/google_fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Poppins-ExtraBold.ttf
          weight: 800




